version: '3.4'

services:
  redisapi:
    image: redisapi
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - 80:80
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
